Updating workflow, adding coverage

diff --git a/.github/workflows/r.yml b/.github/workflows/r.yml
--- a/.github/workflows/r.yml
+++ b/.github/workflows/r.yml
@@ -1,42 +1,59 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-#
-# See https://github.com/r-lib/actions/tree/master/examples#readme for
-# additional example workflows available for the R community.
-
-name: R
-
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: [ "main" ]
+    branches: [main]
   pull_request:
-    branches: [ "main" ]
+    branches: [main]
 
-permissions:
-  contents: read
+name: test-coverage
 
 jobs:
-  build:
+  test-coverage:
     runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       matrix:
         R: [ '3.5.3', '3.6.1', '4.1.3' ]
     name: R ${{ matrix.R }} sample
     steps:
       - uses: actions/checkout@v3
+
       - name: Setup R
         uses: r-lib/actions/setup-r@v2
         with:
-          r-version: ${{ matrix.R }}      
+          r-version: ${{ matrix.R }}
+          use-public-rspm: true
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          extra-packages: any::rcmdcheck
-          needs: check
+          extra-packages: |
+            any::covr
+            any::rcmdcheck
+          needs: |
+            coverage
+            check
           working-directory: 'rtestingexample'
-      - uses: r-lib/actions/check-r-package@v2
+      - name: Test coverage
+        run: |
+          covr::codecov(
+            quiet = FALSE,
+            clean = FALSE,
+            path = "rtestingexample",
+            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
+          )
+        shell: Rscript {0}
+
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v3
         with:
-          args: 'c("--no-manual")'
-          error-on: '"error"'
-          working-directory: 'rtestingexample'
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
